### ISSUE TITLE
Throw an exception when word contains special characters

### ISSUE THREAD

**Issue by larikraun** [larikraun/slackword#1]

**Comment by shalvah** [comment]
Can we explicitly define "special characters"? Or maybe we define allowed chars instead? I'm thinking 0-9 A-Z a-z - and '

**Comment by larikraun** [comment]
Can words contain 0-9-'?

**Comment by shalvah** [comment]
Yup. I'm thinking stuff like "catch-22"?

**Comment by ragingprodigy** [comment]
I don't think this is explicitly required. [This line](https://github.com/larikraun/slackword/blob/83f40ee2ddbcb9414d9fa0ee4d25ed3348fe4162/src/WordRequest.php#L65), from the last commit already fixes the issue in my opinion. The API would just return an empty result because a definition won't be found

**Comment by shalvah** [comment]
Yes, you're right. It's been fixed.
